import Head from 'next/head'
import Layout from '../components/Layout/Layout'
import Image from 'next/image'
import profilePic from '../../public/images/profile/test4.jpg'
import AnimatedText from '@/components/AnimatedText/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons/Icons'
import HireMe from '@/components/HireMe/HireMe'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'


export default function Home() {
  return (
    <>
      <Head className="bg-gradient-to-b from-blue-50 to-red-100">
        <title>Aryan Mishra</title>
        <meta name="description" content="Generated by create next app"/>
        
      </Head>
      <main className='flex items-center bg-gradient-to-b from-blue-50 to-red-100 text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className="flex items-center justify-between w-full">
            <div className='w-1/2 '>
              <Image src={profilePic} alt="MAC" className='w-full h-auto rounded-full'/>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text= "Turning vision into Reality with Code and Design." className='!text-6xl ml-3 !text-left'/>
              <p className='my-4 text-base font-medium '>
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href='./resume2.pdf' target={"_blank"}
                className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                '
                //download={true}
                >Resume <LinkArrow className={"w-6 ml-1"}/></Link>
                <Link href='mailto:aryanmishra3011@gmail.com' target={"_blank"}
                className='ml-4 text-lg font-medium capitalize text-dark underline'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe/>
        <div className='absolute right-8 bottom-8 inline-block w-24'>
          <Image src={lightBulb} alt="MAC" className='w-full h-auto'/>
        </div>
      </main>
    </>
  )
}
